"""initial migration

Revision ID: 2083d9a4bade
Revises: 
Create Date: 2026-03-28 10:37:42.609225

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2083d9a4bade'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('APP_REVIEW', 'SUPPORT_TICKET', 'SURVEY', 'SLACK', 'EMAIL', 'OTHER', name='feedbacksource', native_enum=False, length=50), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ANALYZING', 'ANALYZED', 'ANALYSIS_FAILED', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED', name='feedbackstatus', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_item_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', 'URGENT', name='sentiment', native_enum=False, length=20), nullable=False),
    sa.Column('category', sa.Enum('BUG', 'FEATURE_REQUEST', 'COMPLAINT', 'PRAISE', 'QUESTION', 'SUGGESTION', name='analysiscategory', native_enum=False, length=30), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_llm_response', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('urgency >= 1 AND urgency <= 5', name='ck_urgency_range'),
    sa.ForeignKeyConstraint(['feedback_item_id'], ['feedback_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index('idx_analysis_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_feedback_item_id', ['feedback_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index('idx_feedback_item_id')
        batch_op.drop_index('idx_analysis_created_at')

    op.drop_table('analyses')
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_created_at')

    op.drop_table('feedback_items')
    # ### end Alembic commands ###
